#! /bin/bash

pgrep -x sxhkd > /dev/null || sxhkd &

screens=$(xrandr | grep " connected " | wc -l)

if [ $screens -eq 1 ]; then
	$HOME/.screenlayout/unica_pantalla.sh
  bspc monitor eDP-1 -d I II III IV V VII VIII IX
fi

if [ $screens -eq 2 ]; then
  $HOME/.screenlayout/dos_pantallas.sh
  bspc monitor HDMI-1
  bspc monitor eDP-1 -d I II III IV V VI VII VIII IX
  bspc monitor eDP-1 -s HDMI-1
fi

if [ $screens -eq 3 ]; then
  $HOME/.screenlayout/pantallas.sh
  bspc monitor HDMI-1 -d I II III IV V VI VII VIII IX
  bspc monitor eDP-1
  bspc monitor DP-1
  bspc monitor HDMI-1 -s eDP-1 -t DP-1
fi

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

feh --bg-fill /home/codintdev/Desktop/codintdev/wallpapers/cuphead.jpg &
~/.config/polybar/./launch.sh

bspc config focus_follows_pointer true
picom --experimental-backends &
bspc config border_width 0

xsetroot -cursor_name left_ptr &
